[package]
name = "devotee"
version = "0.1.39"
edition = "2021"
publish = true
authors = ["PSUAN collective", "Hara Red <rtc6fg4.fejg2@gmail.com>"]
description = "Visualization engine"
repository = "https://github.com/PSUAN/devotee"
license = "MIT"
homepage = "https://github.com/PSUAN/devotee"
documentation = "https://docs.rs/devotee"
readme = "README.md"
keywords = ["gamedev", "graphics"]
categories = ["game-engines"]

[features]
default = ["back-softbuffer"]
back-softbuffer = ["dep:devotee-backend-softbuffer"]
back-pixels = ["dep:devotee-backend-pixels"]

[dependencies]
devotee-backend = "0.1.0"
devotee-backend-softbuffer = { version = "0.1.0", optional = true }
devotee-backend-pixels = { version = "0.1.1", optional = true }

instant = "0.1.12"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rodio = { version = "0.17.1", default-features = false, features = ["wav"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rodio = { version = "0.17.1", default-features = false, features = [
    "wav",
    "wasm-bindgen",
] }
web-sys = "0.3.64"
