[package]
name = "devotee"
version = "0.2.0-alpha"
edition = "2021"
publish = true
authors = ["PSUAN collective", "Hara Red <rtc6fg4.fejg2@gmail.com>"]
description = "Visualization engine"
repository = "https://github.com/PSUAN/devotee"
license = "MIT"
homepage = "https://github.com/PSUAN/devotee"
documentation = "https://docs.rs/devotee"
readme = "README.md"
keywords = ["gamedev", "graphics"]
categories = ["game-engines"]

[features]
default = []
wav = ["rodio/wav"]
mp3 = ["rodio/mp3"]

[dependencies]
devotee-backend = "0.2.0-alpha"
instant = "0.1.12"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
rodio = { version = "0.17.1", default-features = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
rodio = { version = "0.17.1", default-features = false, features = [
    "wasm-bindgen",
] }
web-sys = "0.3.64"

[dev-dependencies]
devotee-backend-softbuffer = { version = "0.2.0-alpha" }
